// Langues proposées dans ScriptBoom (code -> consigne donnée à l'IA).
export const LANGS = {
 "fr": "français",
 "en": "anglais",
 "es": "espagnol",
 "pt": "portugais du Portugal",
 "br": "portugais du Brésil",
 "de": "allemand",
 "it": "italien",
 "nl": "néerlandais",
 "ar": "arabe standard",
 "ma": "darija marocaine (dialecte arabe du Maroc tel qu'on le parle à Casablanca, écrit en lettres arabes ; PAS l'arabe littéraire : mots et tournures du quotidien marocain, avec les mots français courants que les Marocains utilisent)",
 "dz": "darija algérienne (dialecte arabe d'Algérie tel qu'on le parle à Alger, écrit en lettres arabes ; PAS l'arabe littéraire : mots du quotidien algérien, avec les mots français courants que les Algériens utilisent)",
 "tn": "dialecte tunisien (derja tunisienne telle qu'on la parle à Tunis, écrite en lettres arabes ; PAS l'arabe littéraire)",
 "eg": "arabe égyptien (dialecte du Caire, écrit en lettres arabes ; PAS l'arabe littéraire)",
 "lb": "arabe levantin (dialecte libanais/syrien, écrit en lettres arabes ; PAS l'arabe littéraire)",
 "tr": "turc",
 "ru": "russe",
 "uk": "ukrainien",
 "pl": "polonais",
 "ro": "roumain",
 "cs": "tchèque",
 "sk": "slovaque",
 "hu": "hongrois",
 "el": "grec",
 "bg": "bulgare",
 "sr": "serbe (alphabet latin)",
 "hr": "croate",
 "bs": "bosnien",
 "sl": "slovène",
 "mk": "macédonien",
 "sq": "albanais",
 "sv": "suédois",
 "no": "norvégien (bokmål)",
 "da": "danois",
 "fi": "finnois",
 "is": "islandais",
 "et": "estonien",
 "lv": "letton",
 "lt": "lituanien",
 "ca": "catalan",
 "eu": "basque",
 "gl": "galicien",
 "he": "hébreu",
 "fa": "persan (farsi)",
 "ur": "ourdou",
 "hi": "hindi",
 "bn": "bengali",
 "pa": "pendjabi (alphabet gurmukhi)",
 "ta": "tamoul",
 "te": "télougou",
 "mr": "marathi",
 "gu": "goudjarati",
 "ne": "népalais",
 "id": "indonésien",
 "ms": "malais",
 "tl": "filipino (tagalog)",
 "vi": "vietnamien",
 "th": "thaï",
 "zh": "chinois mandarin (caractères simplifiés)",
 "ja": "japonais",
 "ko": "coréen",
 "sw": "swahili",
 "am": "amharique",
 "af": "afrikaans",
 "az": "azerbaïdjanais",
 "kk": "kazakh",
 "uz": "ouzbek (alphabet latin)",
 "ka": "géorgien",
 "hy": "arménien"
};
export const ACCENTS = {
 "pt": "accent portugais du Portugal",
 "br": "accent brésilien",
 "ma": "accent marocain authentique (Casablanca), prononciation darija",
 "dz": "accent algérien authentique (Alger)",
 "tn": "accent tunisien authentique (Tunis)",
 "eg": "accent égyptien du Caire",
 "lb": "accent libanais"
};
